### ISSUE TITLE
Crash on load - Redundant texture list for particle modernity: salt

### ISSUE THREAD

**Issue by ScytheIronclaw** [RedGalaxySoftware/TheModernity#1]
The game fails to load, returning the error: java.lang.IllegalStateException: Redundant texture list for particle modernity: salt

#### To Reproduce
Use Minecraft 1.14.4-Forge-28.1.30
Have the Modernity mod in the mods folder
Attempt to launch the game
Game crashes & you get this error.

#### Expected behaviour *(optional)*
I expected the game to make it to the title screen without crashes.

#### Resources *(optional)*

` ---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/14/19 12:16 AM
Description: Rendering overlay

java.lang.IllegalStateException: Redundant texture list for particle modernity:salt
	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:201) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleManager.lambda$null$0(ParticleManager.java:153) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleManager$$Lambda$2497/894025840.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}'

'A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:889)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$346/324507700.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)'

'-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2457692560 bytes (2343 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.0.0+61+ca3b447
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.30.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.30.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.30
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		modernity-INDEV-0.2.0.jar The Modernity {modernity@INDEV-0.2.0 COMMON_SETUP}
		forge-1.14.4-28.1.30-universal.jar Forge {forge@28.1.30 SIDED_SETUP}
		forge-1.14.4-28.1.30-client.jar Minecraft {minecraft@1.14.4 SIDED_SETUP}
	Launched Version: 1.14.4-forge-28.1.30
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.'

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 1700X Eight-Core Processor  `

#### Environment
- Modernity: InDev-0.2.0
- Forge: 28.1.30
- Minecraft: 1.14.4
This was tested in a instance I use for debugging that only had this mod installed.

#### Additional info
N/A

**Comment by FoxSamu** [comment]
It seems that you are using a lower version of forge than recommended. Try loading the mod with forge 28.1.40 (not *.30).

Besides, it seems that I've been unclear about which forge versions are supported. I didn't specify this in the mod info (mods.toml) file so forge won't care about version issues, I'll fix that...

**Comment by ScytheIronclaw** [comment]
I just tested with MC Forge 28.1.40 and 28.1.45 and I still have the same issue.
The game crashes on load and returns the same error.
`java.lang.IllegalStateException: Redundant texture list for particle modernity:salt`

**Comment by FoxSamu** [comment]
I think it's a multithreading issue then. Forge loads mods off-thread. It depends on your hardware which thread is loaded first.
But I'm not sure. I had some troubles with events that did not fire, one of them was the particle registry event...

**Comment by FoxSamu** [comment]
Oops, accidentally closed it, should not be closed...

**Comment by FoxSamu** [comment]
This update should have fixed it: https://github.com/RedGalaxySoftware/TheModernity/releases/tag/v0.2.1-INDEV.
If not, please reopen the issue...

**Comment by itsmeow** [comment]
I was wondering, what causes this issue? I'm confused, trying to solve https://github.com/itsmeow/whisperwoods/issues/1, multiple users have reported this. If you could help, it would be greatly appreciated. Found via GitHub search, useful tool :)
